# Generated by Django 3.0.5 on 2020-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador_nombre', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=1000)),
                ('Fecha_de_ingreso', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_item', models.CharField(max_length=200)),
                ('navbar_item_href_url', models.CharField(max_length=200)),
            ],
        ),
    ]
