# Generated by Django 3.0.5 on 2020-04-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='choice_text',
            new_name='entrenador_descripcion',
        ),
    ]
