# Generated by Django 3.0.5 on 2020-04-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasia', '0002_auto_20200430_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='Fecha_de_ingreso',
            new_name='fecha_de_ingreso',
        ),
    ]
